baseurl = "https://Cateater.github.io" 
languageCode = 'zh-tw'
title = 'My New Hugo Site'
theme = "PaperMod"
buildDrafts = false 
#是否產生草稿(建議選否)
[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10
[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

[params.profileMode]
enabled = true
title = "Cateater1004"
subtitle = "Uh..."
imageUrl = "https://mail.google.com/mail/u/0?ui=2&ik=25748bb3b6&attid=0.1.1&permmsgid=msg-f:1770464750671689903&th=1891f44f7722f8af&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ8QkN2u5JsmdhwW6P8lrPCwbLtL6OQEXmMxeavuMYhm4aaYU8Qg5QtIX9YHEobuo9vy5BT1GI7IPJiIB2fp-JldE3Wqs_s6HMhIwEJIEjWSfmgfjjMD-84o4L8&disp=emb/Cateater1004.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Cateater1004"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Cateater1004"

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視